CONNECT SUBJECT/subject@//localhost:1521/XE;

DROP TABLE employees CASCADE CONSTRAINTS;
DROP TABLE sales CASCADE CONSTRAINTS;

-- EMPLOYEES --
CREATE TABLE employees (
                           employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           first_name  VARCHAR2(50),
                           last_name   VARCHAR2(50),
                           email       VARCHAR2(100) UNIQUE,
                           phone       VARCHAR2(20),
                           hire_date   DATE,
                           job_title   VARCHAR2(50),
                           salary      NUMBER(10, 2),
                           department  VARCHAR2(50)
);

INSERT INTO employees (first_name, last_name, email, phone, hire_date, job_title, salary, department)
VALUES ('John', 'Doe', 'john.doe@example.com', '123-456-7890', TO_DATE('2021-01-15', 'YYYY-MM-DD'), 'Sales Manager', 60000, 'Sales');

INSERT INTO employees (first_name, last_name, email, phone, hire_date, job_title, salary, department)
VALUES ('Jane', 'Smith', 'jane.smith@example.com', '098-765-4321', TO_DATE('2020-05-20', 'YYYY-MM-DD'), 'HR Specialist', 55000, 'Human Resources');

INSERT INTO employees (first_name, last_name, email, phone, hire_date, job_title, salary, department)
VALUES ('Michael', 'Brown', 'michael.brown@example.com', '555-123-4567', TO_DATE('2019-09-10', 'YYYY-MM-DD'), 'Software Engineer', 80000, 'IT');

-- SALES --
CREATE TABLE sales (
                       sale_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       employee_id NUMBER,
                       sale_date DATE,
                       amount NUMBER(10, 2),
                       customer_name VARCHAR2(100),
                       product_name VARCHAR2(100),
                       FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
);

INSERT INTO sales (employee_id, sale_date, amount, customer_name, product_name)
VALUES (1, TO_DATE('2023-07-21', 'YYYY-MM-DD'), 250.50, 'ABC Corp', 'Laptop');

INSERT INTO sales (employee_id, sale_date, amount, customer_name, product_name)
VALUES (1, TO_DATE('2023-08-10', 'YYYY-MM-DD'), 120.75, 'XYZ Inc', 'Printer');

INSERT INTO sales (employee_id, sale_date, amount, customer_name, product_name)
VALUES (2, TO_DATE('2024-10-15', 'YYYY-MM-DD'), 500.00, 'Tech Solutions', 'Office Desk');

-- MATH --
CREATE TABLE math (
                      a NUMBER,
                      b NUMBER
);

INSERT INTO math (a, b) VALUES (2, 11);
INSERT INTO math (a, b) VALUES (5, 20);
INSERT INTO math (a, b) VALUES (3, 14);
INSERT INTO math (a, b) VALUES (1, 8);
INSERT INTO math (a, b) VALUES (4, 17);
INSERT INTO math (a, b) VALUES (7, 26);

-- QUESTION MANAGEMENT --
CREATE TABLE questions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_resolved NUMBER(1,0) DEFAULT 0
);

INSERT INTO questions (id, is_resolved) VALUES (1,0);
INSERT INTO questions (id, is_resolved) VALUES (2,0);
INSERT INTO questions (id, is_resolved) VALUES (3,0);
INSERT INTO questions (id, is_resolved) VALUES (4,0);
INSERT INTO questions (id, is_resolved) VALUES (5,0);
INSERT INTO questions (id, is_resolved) VALUES (6,0);

COMMIT;